on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Prepare release

jobs:
  release-please:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{secrets.RELEASE_PLEASE_PAT}}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
